version: '3'
services:
  web:
    build: .
    ports:
      - "80:80"
  localtunnel:
    build:
      context: .
      dockerfile: Dockerfile-lt
    links:
      - web
    command:
      --local-host web --port 80 --subdomain georgevbarbu      
